apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKERHUB_USERNAME}/uptime-backend:latest
        ports:
        - containerPort: 4000
          name: monitor
        - containerPort: 4001
          name: email
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-username
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-password
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-port
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: smtp-pass
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - name: monitor
    port: 80
    targetPort: 4000
  - name: email
    port: 81
    targetPort: 4001
  type: ClusterIP 